[workspace]
members = ["01-pure-rust"]
resolver = "2"

[workspace.dependencies]
napi = { version = "3.0.0", default-features = false, features = ["napi3"] }
napi-derive = "3.0.0"
napi-build = "2"
lz-str = "0.2"

[profile.release]
lto = true
strip = "symbols"